
version: "3.3"
services:
  mysql:
    name: teamcity-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${teamcity_db}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${mysql_user}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${mysql_password}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${mysql_password_root}'
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - teamcity

  server:
    name: teamcity-server
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - "${MAIN_PORT}:8111"
    volumes:
      - ./server/data:/data/teamcity_server/datadir
      - ./server/logs:/opt/teamcity/logs
    networks:
      - teamcity
    depends_on:
      - mysql
      
  teamcity-agent_1:
    restart: always
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=${SERVER_HOST}:${MAIN_PORT}
      - AGENT_NAME=agent_1
    volumes:
      - ./agent_1/data:/data/teamcity_agent/conf
    networks:
      - teamcity
      
  teamcity-agent_2:
    restart: always
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=${SERVER_HOST}:${MAIN_PORT}
      - AGENT_NAME=agent_2
    volumes:
      - ./agent_2/data:/data/teamcity_agent/conf
    networks:
      - teamcity      
      
networks:
  teamcity:
    driver: bridge
      
