
version: "3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${teamcity_db}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${mysql_user}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${mysql_password}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${mysql_password_root}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.01:3306:3306'      
    volumes:
      - ./mysql:/var/lib/mysql

server:
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - "${MAIN_PORT}:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs

  teamcity-minimal-agent:
    restart: always
    image: jetbrains/teamcity-minimal-agent
    environment:
      - SERVER_URL=http://${AGENT_HOST}:8111
      - AGENT_NAME=minimal_agent

