
version: "3.3"
services:
  teamcity-mysql:
    container_name: teamcity-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${teamcity_db}'
      MYSQL_USER: '${mysql_user}'
      MYSQL_PASSWORD: '${mysql_password}'
      MYSQL_ROOT_PASSWORD: '${mysql_password_root}'
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - teamcity

  teamcity-server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - "${MAIN_PORT}:8111"
    volumes:
      - ./server/data:/data/teamcity_server/datadir
      - ./server/logs:/opt/teamcity/logs
    networks:
      - teamcity
    depends_on:
      - teamcity-mysql
      
  teamcity-agent_1:
    container_name: teamcity-agent_1
    image: jetbrains/teamcity-agent
    restart: always
    environment:
      - SERVER_URL=teamcity-server:8111
      - AGENT_NAME=agent_1
    volumes:
      - ./agent_1/data:/data/teamcity_agent/conf
    networks:
      - teamcity
    depends_on:
      - teamcity-server
            
      
  teamcity-agent_2:
    container_name: teamcity-agent_2
    image: jetbrains/teamcity-agent
    restart: always
    environment:
      - SERVER_URL=teamcity-server:8111
      - AGENT_NAME=agent_2
    volumes:
      - ./agent_2/data:/data/teamcity_agent/conf
    networks:
      - teamcity
    depends_on:
      - teamcity-server

  teamcity-agent_3:
    container_name: teamcity-agent_3
    image: jetbrains/teamcity-agent
    restart: always
    environment:
      - SERVER_URL=teamcity-server:8111
      - AGENT_NAME=agent_3
    volumes:
      - ./agent_3/data:/data/teamcity_agent/conf      
    networks:
      - teamcity
    depends_on:
      - teamcity-server

networks:
  teamcity:
    driver: bridge
      
