
version: "3.3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${teamcity_db}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${mysql_user}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${mysql_password}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${mysql_password_root}'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - teamcity

  server:
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - "${MAIN_PORT}:8111"
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    networks:
      - teamcity
    depends_on:
      - mysql
      
  teamcity-minimal-agent:
    restart: always
    image: jetbrains/teamcity-minimal-agent
    environment:
      - SERVER_URL=http://${AGENT_HOST}:8111
      - AGENT_NAME=minimal_agent
    networks:
      - teamcity
      
  
networks:
  teamcity:
    # Use a custom driver
    driver: bridge
      
